name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev-*

jobs:
  prepare_checks:
    name: Prepare checks - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache virtualenv for Python ${{ matrix.python_version }}
        uses: syphar/restore-virtualenv@v1
        id: cache_virtualenv
      - name: Cache pip download for Python ${{ matrix.python_version }}
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache_virtualenv.outputs.cache-hit != 'true'
      - name: Install requirements
        run: pip install -r requirements.txt
        if: steps.cache_virtualenv.outputs.cache-hit != 'true'
      - name: Install development requirements
        run: pip install -r requirements-dev.txt
        if: steps.cache_virtualenv.outputs.cache-hit != 'true'

  tests:
    name: Tests - Python ${{ matrix.python_version }}
    needs:
      - prepare_checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache virtualenv for Python ${{ matrix.python_version }}
        uses: syphar/restore-virtualenv@v1
        id: cache_virtualenv
      - name: Run unit tests
        run: pytest --cov=src --cov-report=term-missing --junitxml=junit/test-results.xml --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: python-${{ matrix.python_version }}-coverage
          path: .coverage
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python_version }}
          path: junit/test-results.xml
        if: ${{ always() }}

  security:
    name: Security
    needs:
      - prepare_checks
    continue-on-error: True
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache virtualenv for Python 3.11
        uses: syphar/restore-virtualenv@v1
        id: cache_virtualenv
      - name: Audit packages
        run: pip-audit

  code_analyse:
    name: Code analyse - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    needs:
      - prepare_checks
      - tests
    strategy:
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache virtualenv for Python ${{ matrix.python_version }}
        uses: syphar/restore-virtualenv@v1
      - name: Check code format with black
        run: |
          black --version
          black --diff --check $(git ls-files '*.py')
      - name: Lint with flake8
        run: |
          flake8 --version
          flake8 --show-source --statistics $(git ls-files '*.py')
      - name: Lint with mypy
        run: mypy $(git ls-files '*.py')
      - name: Lint with pylint
        run: |
          pylint --version
          pylint $(git ls-files '*.py')
      - name: Lint with yamllint
        run: |
          yamllint --version
          yamllint $(git ls-files '*.yaml') $(git ls-files '*.yml')

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: python-3.11-coverage
      - name: Create coverage badge
        uses: tj-actions/coverage-badge-py@v2
      - name: Verify coverage badge changed
        uses: tj-actions/verify-changed-files@v14
        id: changed_files
        with:
          files: coverage.svg
      - name: Commit coverage badge
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "noreply@superbox.one"
          git config --local user.name "Github Workflow"
          git add coverage.svg
          git commit -m "Updated coverage.svg"
      - name: Push changes
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
