name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  parameters:
    name: Parameters
    uses: superbox-dev/python-package-workflows/.github/workflows/parameters.yml@main
    with:
      python-version: 3.8 3.9 3.10 3.11

  validate:
    name: Validate
    if: |
      contains(fromJSON('["tag", "branch"]'), github.ref_type)
      && github.ref_name != 'main'
      && !endsWith(github.ref_name, '/merge')
    uses: superbox-dev/python-package-workflows/.github/workflows/validate-version.yml@main
    needs:
      - parameters
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}

  unit-testing:
    name: Unit testing
    uses: superbox-dev/python-package-workflows/.github/workflows/unit-testing.yml@main
    needs:
      - parameters
    with:
      python-version: ${{ needs.parameters.outputs.python-version }}

  coverage:
    name: Coverage
    uses: superbox-dev/python-package-workflows/.github/workflows/coverage.yml@main
    needs:
      - parameters
      - unit-testing
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}

  code-analyse:
    name: Code analyse
    uses: superbox-dev/python-package-workflows/.github/workflows/code-analyse.yml@main
    needs:
      - parameters
    with:
      python-version: ${{ needs.parameters.outputs.python-version }}

  security:
    name: Security
    uses: superbox-dev/python-package-workflows/.github/workflows/security.yml@main
    needs:
      - parameters
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}

  build:
    name: Build
    if: |
      contains(fromJSON('["tag", "branch"]'), github.ref_type)
      && github.ref_name != 'main'
      && !endsWith(github.ref_name, '/merge')
    uses: superbox-dev/python-package-workflows/.github/workflows/build-python-package.yml@main
    needs:
      - parameters
      - unit-testing
      - code-analyse
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}
      package-version: ${{ needs.parameters.outputs.package-version }}

  release:
    name: Release
    if: github.ref_type == 'tag'
    uses: superbox-dev/python-package-workflows/.github/workflows/release.yml@main
    needs:
      - parameters
      - validate
      - build
    with:
      package-name: ${{ needs.parameters.outputs.package-name }}
      package-version: ${{ needs.parameters.outputs.package-version }}

  publish:
    name: Publish
    needs:
      - release
    uses: superbox-dev/python-package-workflows/.github/workflows/publish.yml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
