name: Development

on:
  workflow_dispatch:

jobs:
  build_python_package:
    name: Build python package
    needs:
      - tests
    uses: superbox-dev/python-package-workflows/.github/workflows/build-python-package.yml@main
