name: Parameters

on:
  workflow_call:
    inputs:
      python-version:
        required: True
        default: '3.8 3.9 3.10 3.11'
        type: string
    outputs:
      params:
        description: Parameters to be used in other jobs.
        value: ${{ fromJson(jobs.set-up-parameters.outputs.params) }}

jobs:
  set-up-parameters:
    name: Set up parameters
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.params.outputs.params }}
    steps:
      - name: Generate 'params'
        id: params
        shell: python
        run: |
          from os import environ

          params = {
            'python-version': '${{ inputs.python-version }}'.split(' '),
          }

          with open(environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as gho:
              gho.write(f"params={params!s}\n")
          
          print("Parameters:")
          print(params)
