name: Parameters

on:
  workflow_call:
    inputs:
      python-version:
        required: True
        default: '3.8 3.9 3.10 3.11'
        type: string
    outputs:
      python-version:
        value: ${{ jobs.set-up-parameters.outputs.python-version }}

jobs:
  set-up-parameters:
    name: Set up parameters
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.params.outputs.python-version }}
    steps:
      - name: Generate 'params'
        id: params
        shell: python
        run: |
          from os import environ
          import json

          python_version = json.dumps('${{ inputs.python-version }}'.split(' '))

          with open(environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as gho:
              gho.write(f"python-version={python_version!s}\n")
          
          print("Python version:", python_version)
