name: Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:
  parameters:
    name: Parameters
    uses: ./.github/workflows/parameters.yml
    with:
      python-version: 3.8 3.9 3.10 3.11

  unit-testing:
    # if: |
    #   github.ref == 'pull_request'
    #   || github.ref_type == 'tag'
    name: Unit testing
    uses: ./.github/workflows/unit-testing.yml
    needs:
      - parameters
    with:
      python-version: ${{ needs.parameters.outputs.python-version }}

  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage.yml
    needs:
      - parameters
      - unit-testing
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}

  code-analyse:
    name: Code analyse
    uses: ./.github/workflows/code-analyse.yml
    needs:
      - parameters
    with:
      python-version: ${{ needs.parameters.outputs.python-version }}

  security:
    name: Security
    uses: ./.github/workflows/security.yml
    needs:
      - parameters
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs:
      - parameters
      - unit-testing
      - code-analyse
    with:
      latest-python-version: ${{ needs.parameters.outputs.latest-python-version }}
      package-name: ${{ needs.parameters.outputs.package-name }}
      package-alternate-name: ${{ needs.parameters.outputs.package-alternate-name }}
      package-version: ${{ needs.parameters.outputs.package-version }}

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs:
      - parameters
      - build
    with:
      package-name: ${{ needs.parameters.outputs.package-name }}
      package-version: ${{ needs.parameters.outputs.package-version }}
