name: Release

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    name: Tests
    uses: superbox-dev/python-package-workflows/.github/workflows/tests.yml@main

  build_python_package:
    name: Build python package
    uses: superbox-dev/python-package-workflows/.github/workflows/build-python-package.yml@main
    needs:
      - tests

  release:
    name: Release
    permissions:
      id-token: write
    uses: superbox-dev/python-package-workflows/.github/workflows/release.yml@main
    needs:
      - build_python_package
