name: Tests

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string
      python-versions:
        required: True
        type: string

jobs:
  validate:
    name: Validate
    if: |
      contains(fromJSON('["tag", "branch"]'), github.ref_type)
      && github.ref_name != 'main'
      && !endsWith(github.ref_name, '/merge')
    uses: superbox-dev/python-package-workflows/.github/workflows/validate-version.yml@main
    with:
      latest-python-version: ${{ inputs.latest-python-version }}

  unit-testing:
    name: Unit testing
    uses: superbox-dev/python-package-workflows/.github/workflows/unit-testing.yml@main
    with:
      python-versions: ${{ inputs.python-versions }}

  coverage:
    name: Coverage
    uses: superbox-dev/python-package-workflows/.github/workflows/coverage.yml@main
    needs:
      - unit-testing
    with:
      latest-python-version: ${{ inputs.latest-python-version }}

  code-analyse:
    name: Code analyse
    uses: superbox-dev/python-package-workflows/.github/workflows/code-analyse.yml@main
    with:
      python-versions: ${{ inputs.python-versions }}

  security:
    name: Security
    uses: superbox-dev/python-package-workflows/.github/workflows/security.yml@main
    with:
      latest-python-version: ${{ inputs.latest-python-version }}
