name: Validate

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string
      package-version:
        required: True
        type: string

jobs:
  validate-version:
    name: Validate version
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.latest-python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python }}

      - name: Check tag ${{ github.ref_name }}
        run: |
          [[ "${{ github.ref_name }}" == "main" ]] || exit 0
          [[ "${{ github.ref_name }}" == */merge* ]] || exit 0

          ref_name="${{ github.ref_name }}"
          tag_version="${ref_name/.dev/}"

          if [ "${tag_version}" != "${{ inputs.package-version }}" ]; then
            echo "Version number in package does not match tag! (${tag_version} vs. ${{ inputs.package-version }})."
            exit 1
          fi
